### ISSUE TITLE
Create PSP `host-namespaces` policy

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-hub#23]
Write a Kubewarden policy that implements the [host namespaces psp](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#host-namespaces).

## Configuration

```yaml
allowHostPID: true
allowHostIPC: false
allowHostNetwork: false
allowedHostPortRange: [1024, 2048]
```

Default behaviour of the configuration knobs
* `hostPID` and `hostIPC` and `hostNetwork`: they are all `false`
* `allowedHostPortRange`: when empty, no host port can be used

Settings validation:
* allowedHostPortRange: this is an array that must have only two values. The first value is the minimum, the second is the maximum. Obviously minimum cannot be major than maximum

**Comment by ereslibre** [comment]
On PodSecurityPolicies the allowed host port range is a list of ranges, such as:

```
  hostPorts:
  - min: 0
    max: 65535
```

This policy could allow this as well, by allowing a list of `allowedHostPortRanges`, such as:

```
allowedHostPortRanges:
  - portMin: 80
    portMax: 443
  - portMin: 8000
    portMax: 8443
```

in a single policy instance.
