### ISSUE TITLE
Create PSP `allowedHostPaths`

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-hub#26]
Create a Kubewarden policy that replaces the [allowedHostPaths PSP](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#volumes-and-file-systems)

## Configuration

```yaml
allowedHostPaths:
- pathPrefix: "/foo"
  readOnly: true
- pathPrefix: "/bar"
  readOnly: false
```

The `allowedHostPaths` is a list of host paths that are allowed to be used by hostPath volumes. An empty list means there is no restriction on host paths used.

This is defined as a list of objects with a single pathPrefix field, which allows hostPath volumes to mount a path that begins with an allowed prefix, and a readOnly field indicating it must be mounted read-only.

Default value:
* allowedHostPaths is an empty list -> no restriction is put in place

### Special behaviour

It's possible to have host paths sharing part of the prefix. When that happens, the readOnly attribute of the most specific path takes precedence.

For example, given the following configuration:

```yaml
allowedHostPaths:
- pathPrefix: "/foo"
  readOnly: false
- pathPrefix: "/foo/bar"
  readOnly: true
```
Paths such as `/foo/bar/dir1`, `/foo/bar` must be read only.

### Settings validation

Each entry of the `allowedHostPaths` must have both a `pathPrefix` and a `readOnly` attribute.
