### ISSUE TITLE
Create PSP `SELinux`

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-hub#29]
Create a Kubewarden policy that replaces the [SELinux PSP](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#selinux).

# Configuration

```yaml
allowedSELinuxOptions:
- level: s0:c123,c456
  role: object_r
  type: svirt_sandbox_file_t
  user: system_u
- level: s1:c234,c567
  user: sysadm_u
  role: sysadm_r
  type: svirt_lxc_net_t
```

Note well about `seLinuxOptions`:
> The SELinux context to be applied to all containers. If unspecified, the container runtime will allocate a random SELinux context for each container. May also be set in SecurityContext. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence for that container.

That means the policy must look for the `seLinuxOptions` both inside of the Pod and inside of the containers (including `initContainters`)
